name: teleop
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h4777abc_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py310heccc163_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.3=h86ecc28_0
  - krb5=1.21.3=h50a48e9_0
  - ld_impl_linux-aarch64=2.44=h9df1782_2
  - libedit=3.1.20250104=pl5321h976ea20_0
  - libffi=3.4.6=he21f813_1
  - libgcc=15.2.0=he277a41_7
  - libgcc-ng=15.2.0=he9431aa_7
  - libgomp=15.2.0=he277a41_7
  - liblzma=5.8.1=h86ecc28_2
  - liblzma-devel=5.8.1=h86ecc28_2
  - libnsl=2.0.1=h86ecc28_1
  - libsodium=1.0.20=h68df207_0
  - libsqlite=3.50.4=h022381a_0
  - libstdcxx=15.2.0=h3f4de04_7
  - libstdcxx-ng=15.2.0=hf1166c9_7
  - libuuid=2.41.2=h3e4203c_0
  - libzlib=1.3.1=h86ecc28_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=ha32ae93_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h8e36d6e_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py310h5b55623_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.0=h2265c99_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyzmq=27.1.0=py310h5df05d2_0
  - readline=8.2=h8382b9d_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.4=he8854b5_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h5688188_102
  - tornado=6.5.2=py310ha7967c6_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=h2dbfc1b_2
  - xz-gpl-tools=5.8.1=h2dbfc1b_2
  - xz-tools=5.8.1=h86ecc28_2
  - zeromq=4.3.5=hefbcea8_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==15.1.0
      - blinker==1.9.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - cmake==4.1.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.3.0
      - datasets==4.1.1
      - deepdiff==8.6.1
      - diffusers==0.35.2
      - dill==0.4.0
      - draccus==0.10.0
      - einops==0.8.1
      - evdev==1.9.2
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - flask==3.1.2
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gymnasium==1.2.3
      - h5py==3.15.1
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - huggingface-hub==0.35.3
      - idna==3.11
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - inquirerpy==0.3.4
      - itsdangerous==2.2.0
      - jsonlines==4.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lerobot==0.4.2
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mergedeep==1.3.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - narwhals==2.12.0
      - nbformat==5.10.4
      - networkx==3.4.2
      - numpy==2.2.6
      - open3d==0.18.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orderly-set==5.5.0
      - pandas==2.3.3
      - pfzy==0.3.4
      - pillow==12.0.0
      - pip==25.3
      - plotly==6.5.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pynput==1.8.1
      - pyparsing==3.2.5
      - pyserial==3.5
      - python-xlib==0.33
      - pytz==2025.2
      - pyyaml-include==1.4.1
      - rby1-sdk==0.7.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rerun-sdk==0.26.2
      - retrying==1.4.2
      - rpds-py==0.29.0
      - safetensors==0.7.0
      - scipy==1.15.3
      - sentry-sdk==2.48.0
      - smmap==5.0.2
      - sympy==1.14.0
      - termcolor==3.2.0
      - toml==0.10.2
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - wandb==0.21.4
      - werkzeug==3.1.3
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/nvidia/miniforge3/envs/teleop
